server:
  port: 8182

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#  ensures using offsets when reading from partition. it makes not to read again what already has been read.
#  the offset is like a marker where it has read last.
  consumer-group-id: twitter-topic-consumer
#  start reading from the beginning of the partition
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
#  allow consuming data in batches
  batch-listener: true
#  start listening from topic after ensuring the topic is already there. so we set it to false here. will listen when topics are up.
  auto-startup: true
#  is equal to the partitions number
  concurrency-level: 3
#  required for heartbeat reads. specified amount of time in which the kafka broker needs to get a heartbeat signal
#  from consumer. otherwise consumer is treated as dead.
  session-timeout-ms: 10000
#  frequency of heartbeat signals
  heartbeat-interval-ms: 3000
#  if message processing is too heavy and takes more then the interval configured then coordinator marks the consumer
#  to leave the group. The value should be set according to the expected processing time requirements.
  max-poll-interval-ms: 300000
#  max records to fetch in each poll
  max-poll-records: 500
#  max bytes to fetch in each poll
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
#  how long we'll wait for at lest one record is available. having very low value may cause CPU stall - utilizes CPU
#  but no actual progress
  poll-timeout-ms: 100

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000
