logging:
  level.org.apache.kafka.clients.producer=DEBUG

twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy # google compression impl
  acks: all # all because we want to receive acknowledgments from all the replicas to be more resilient; 1 - wait for current broker; 0 - no ack
  batch-size: 16384 # 16KB collect messages into batches
  batch-size-boost-factor: 100
  linger-ms: 5 # If the batch is not full, Kafka will wait up to linger.ms milliseconds to gather more messages before sending that batch anyway.
  request-timeout-ms: 60000
  retry-count: 5